pnpm wasm:dev got this error it-bridge/web-next/wasm) error[E0432]: unresolved import `shared::protocol::rpc::auth_provider::EnvAppAuthTokenProvider`   --> web-next/wasm/src/di_container.rs:25:58    | 25 | ...vider, EnvAppAuthTokenProvider};    |           ^^^^^^^^^^^^^^^^^^^^^^^ no `EnvAppAuthTokenProvider` in `protocol::rpc::auth_provider`
error[E0560]: struct `AuthProvider` has no field named `app_auth_token`
  --> web-next/wasm/src/di_container.rs:96:13
   |
96 |             app_auth_token: Box::new(EnvAppA...
   |             ^^^^^^^^^^^^^^ `AuthProvider` does not have this field
   |
   = note: all struct fields are already assigned

Some errors have detailed explanations: E0432, E0560.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `wasm` (lib) due to 2 previous errors
Error: Compiling your crate to WebAssembly failed
Caused by: Compiling your crate to WebAssembly failed
Caused by: failed to execute `cargo build`: exited with exit status: 101
  full command: cd "/Users/tiendang/Projects/bit-bridge/web-next/wasm" && "cargo" "build" "--lib" "--target" "wasm32-unknown-unknown"
 ELIFECYCLE  Command failed with exi