Fix this issue on wasm build    Compiling wasm v0.1.0 (/Users/tiendang/Projects/bit-bridge/web-next/wasm) error[E0046]: not all trait items implemented, missing: `cloud_server`   --> web-next/wasm/src/executor/rpc.rs:10:1    | 10 | impl NativeRpc<Client> for NativeRpcImpl {    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `cloud_server` in implementation    |    = help: implement the missing item: `fn cloud_server(&self) -> &CloudServer<Client> { todo!() }`
For more information about this error, try `rustc --explain E0046`.
error: could not compile `wasm` (lib) due to 1 previous error
Error: Compiling your crate to WebAssembly failed
Caused by: Compiling your crate to WebAssembly failed
Caused by: failed to execute `cargo build`: exited with exit status: 101
  full command: cd "/Users/tiendang/Projects/bit-bridge/web-next/wasm" && "cargo" "build" "--lib" "--target" "wasm32-unknown-unknown"
 ELIFECYCLE  Command failed with exit code 1.